[package]
name = "vericrypt-fuzz"
version = "0.0.0"
edition = "2021"
publish = false

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"

[dependencies.vericrypt]
path = ".."

[[bin]]
name = "parse_pem"
path = "fuzz_targets/parse_pem.rs"
test = false
doc = false

[[bin]]
name = "parse_der"
path = "fuzz_targets/parse_der.rs"
test = false
doc = false

[[bin]]
name = "parse_csv"
path = "fuzz_targets/parse_csv.rs"
test = false
doc = false

[[bin]]
name = "parse_json"
path = "fuzz_targets/parse_json.rs"
test = false
doc = false
