use crate::errors::VeriCryptError;
use std::path::PathBuf;

/// Generate a self-contained verification script for regulators.
///
/// The script invokes vericrypt-verify on the report.pqc in the same directory.
/// Regulators can run it without understanding VeriCrypt internals.
pub fn write_verification_script(output_dir: &PathBuf) -> Result<(), VeriCryptError> {
    let script_path = output_dir.join("verify.sh");

    let script = format!(
        r#"#!/bin/bash
# VeriCrypt Report Verification Script
# Generated by VeriCrypt v{}
#
# Usage: bash verify.sh [path to vericrypt-verify binary]
#
# This script verifies the integrity and authenticity of the .pqc report
# in this directory. It checks:
#   1. SLH-DSA signature validity (NIST FIPS 205)
#   2. Merkle root consistency
#   3. Optional TEE attestation
#   4. Certificate chain to Root Verity Authority

set -e

VERIFIER="${{1:-vericrypt-verify}}"
REPORT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPORT_FILE="$REPORT_DIR/report.pqc"

if [ ! -f "$REPORT_FILE" ]; then
    echo "ERROR: report.pqc not found in $REPORT_DIR"
    exit 1
fi

echo "=== VeriCrypt Report Verification ==="
echo "Report: $REPORT_FILE"
echo ""

if command -v "$VERIFIER" &> /dev/null; then
    "$VERIFIER" "$REPORT_FILE"
else
    echo "VeriCrypt verifier not found at: $VERIFIER"
    echo "Download from: https://verity.io/vericrypt-verify"
    echo ""
    echo "Manual verification checks:"
    echo "  1. Report file: $REPORT_FILE"
    echo "  2. CBOM file: $REPORT_DIR/cbom.json"
    echo "  3. Roadmap file: $REPORT_DIR/roadmap.md"
    exit 1
fi
"#,
        env!("CARGO_PKG_VERSION")
    );

    std::fs::write(&script_path, script).map_err(|e| VeriCryptError::Io(e))?;

    // Make the script executable on Unix
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let mut perms = std::fs::metadata(&script_path)
            .map_err(|e| VeriCryptError::Io(e))?
            .permissions();
        perms.set_mode(0o755);
        std::fs::set_permissions(&script_path, perms).map_err(|e| VeriCryptError::Io(e))?;
    }

    Ok(())
}
